# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=32, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(blank=True, null=True)),
                ('datetime', models.DateField(auto_now=True, verbose_name='\u65f6\u95f4')),
                ('tag', models.CharField(default='none', max_length=32, verbose_name='\u6587\u7ae0\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u6211\u7684\u535a\u5ba2',
                'verbose_name_plural': '\u6211\u7684\u535a\u5ba2',
            },
        ),
    ]
